- hosts: all
  sudo: yes

  vars:
    minecraft_logstash_elasticsearch_host: logstash-web-indexer
    minecraft_logstash_elasticsearch_port: 9300
    logstash_opts: agent -f {{ logstash_conf_file }}

  roles:
    - role: "logstash"
      logstash_conf_template: ./logstash.d/minecraft-server.conf
    - role: "minecraft"
