- hosts: all
  sudo: yes

  vars_files:
    - shared-vars.yaml

  vars:
    minecraft_logstash_redis_host: "{{ logstash_redis_host }}"
    minecraft_logstash_redis_port: "{{ logstash_redis_port }}"
    logstash_opts: agent -f {{ logstash_conf_file }}

  roles:
    - role: "logstash"
      logstash_conf_template: ./logstash.d/minecraft-server.conf
    - role: "minecraft"
