minecraft_binary: minecraft_server.1.7.2.jar
minecraft_bin_dir: /opt/lib/minecraft
minecraft_chdir: /var/minecraft
minecraft_user: minecraft
minecraft_group: minecraft

minecraft_Xms: 1G
minecraft_Xmx: 2G
