- name: create group
  group: name={{ minecraft_group }}
         state=present
         system=yes

- name: make user
  user: name={{ minecraft_user }}
        group={{ minecraft_group }}
        createhome=no
        system=yes
        state=present

- name: Make Directories
  file: path={{ item }}
        state=directory
        owner={{ minecraft_user }}
        group={{ minecraft_group }}
        mode=0755
        recurse=yes
  with_items: [ "{{ minecraft_bin_dir }}", "{{ minecraft_chdir }}" ]

- name: Get Minecraft Server jar
  copy: src={{ minecraft_binary }}
        dest={{ minecraft_bin_dir }}/minecraft-server.jar
        owner={{ minecraft_user }}
        group={{ minecraft_group }}
        mode=0555

- name: Setup Log4j
  template: src=log4j2.xml.j2
            dest={{ minecraft_bin_dir}}/log4j2.xml
            owner={{ minecraft_user }}
            group={{ minecraft_group }}
            mode=0444

- name: install minecraft server upstart
  template: src=minecraft-server.conf.j2
            dest=/etc/init/minecraft-server.conf
            mode=0644

- name: Start up Minecraft Server
  service: name=minecraft-server
           state=started

