minecraft_binary: minecraft_server.1.7.2.jar
minecraft_bin_dir: /opt/lib/minecraft
minecraft_chdir: /var/minecraft
minecraft_user: minecraft
minecraft_group: minecraft

minecraft_java_opts: "-Xms1G -Xmx2G"
minecraft_logging_opts: "-Dlog4j.configurationFile={{ minecraft_bin_dir }}/log4j2.xml"
