---
- name: Install Riemann
  command: dpkg -i /vagrant/ansible/roles/riemann/files/riemann_0.2.4_all.deb

- name: install confs
  template: src={{ riemann_config }}
        dest=/etc/riemann/riemann.config
        mode=0644

- name: restart riemann
  service: name=riemann
           state=reloaded
           enabled=yes
