- hosts: all
  sudo: yes

  vars_files:
    - shared-vars.yaml

  roles:
    - role: riemann
      riemann_config: riemann-graphite-relay.config.j2

    - role: collectd
      carbon_port: "{{ carbon_relay_port }}"
      carbon_host: "{{ carbon_relay_host }}"

    - role: graphite
