- hosts: all
  sudo: yes

  vars_files:
    - shared-vars.yaml

  roles:
    - role: riemann-tools
    - role: riemann-tools
      riemann_tools_cmd: riemann-net
    - role: graphite
    - role: logstash
      logstash_run_as: root
      logstash_conf_template: "logstash.d/graphite.conf.j2"
