- hosts: all
  sudo: yes

  roles:
    - role: system_user
      system_user: "{{ logstash_user }}"
      system_user_dirs:
        - "{{ logstash_bin_dir }}"
        - "{{ logstash_home }}"
        - "{{ logstash_conf_dir }}"
    - role: "logstash"
      logstash_conf_template: logstash.d/logstash-web-indexer.conf
