- hosts: all
  sudo: yes

  vars_files:
    - shared-vars.yaml

  vars:
    minecraft_logstash_redis_host: "{{ logstash_redis_host }}"
    minecraft_logstash_redis_port: "{{ logstash_redis_port }}"

  roles:
    - role: minecraft
    - role: logstash
      logstash_run_as: "{{ minecraft_user }}"
      logstash_run_group: "{{ minecraft_group }}"
      logstash_home: "{{ minecraft_chdir }}"
      logstash_conf_template: "logstash.d/minecraft-server.conf.j2"
      logstash_opts: agent -f {{ logstash_conf_file }}
      logstash_upstart_name: "minecraft-logging"

  tasks:
    - service: name=minecraft-server
               state=restarted

