- hosts: all
  sudo: yes

  vars_files:
    - shared-vars.yaml

  roles:
    - role: riemann
      riemann_config: riemann-graphite-relay.config.j2

    - role: collectd
      carbon_port: "{{ carbon_relay_port }}"
      carbon_host: "{{ carbon_relay_host }}"

    - role: minecraft

    - role: logstash
      logstash_run_as: "{{ minecraft_user }}"
      logstash_run_group: "{{ minecraft_group }}"
      logstash_home: "{{ minecraft_chdir }}"
      logstash_conf_template: "logstash.d/minecraft-server.conf.j2"
      logstash_opts: agent -f {{ logstash_conf_file }}
      logstash_upstart_name: "minecraft-logging"

  tasks:
    - service: name=minecraft-server
               state=restarted

