- hosts: all
  sudo: yes

  vars_files:
    - shared-vars.yaml

  roles:
    - role: riemann-tools
    - role: minecraft

    - role: logstash
      logstash_run_as: root
      logstash_conf_template: "logstash.d/minecraft-server.conf.j2"
      logstash_opts: agent -f {{ logstash_conf_file }}

  tasks:
    - service: name=minecraft-server
               state=restarted

