- hosts: all
  sudo: yes

  vars_files:
    - shared-vars.yaml

  vars:
    minecraft_logstash_redis_host: "{{ logstash_redis_host }}"
    minecraft_logstash_redis_port: "{{ logstash_redis_port }}"
    logstash_opts: agent -f {{ logstash_conf_file }}

  roles:
    - role: minecraft
    - role: logstash
      logstash_user: "{{ minecraft_user }}"
      logstash_group: "{{ minecraft_group }}"
      logstash_home: "{{ minecraft_chdir }}"
      logstash_conf_dir: "{{ minecraft_chdir }}"
      logstash_conf_template: "logstash.d/minecraft-server.conf.j2"
