- hosts: all
  sudo: yes

  vars_files:
    - shared-vars.yaml

  roles:
    - role: riemann-tools
    - role: riemann-tools
      riemann_tools_cmd: riemann-net
    - role: riemann
    - role: riemann-dash
