# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "saucy64-lxc"
  config.vm.box_url = "http://bit.ly/vagrant-lxc-saucy64-2013-10-23"

  config.vm.provision :shell, path: "provision.sh"
end
