- name: Get Logstash jar
  copy: src={{ logstash_binary }}
        dest={{ logstash_bin_dir }}/logstash-flat.jar
        owner={{ logstash_user }}
        group={{ logstash_group }}
        mode=0555

- name: Install logstash Conf
  template: src={{ logstash_conf_template }}
            dest={{ logstash_conf_file }}
            mode=0664
  when: logstash_conf_template != ""

- name: install logstash into upstart
  template: src=logstash.conf.j2
            dest=/etc/init/{{ logstash_upstart_name }}.conf
            mode=0664

- name: Start up logstash
  service: name={{ logstash_upstart_name }}
           state=started

