logstash_binary: logstash-1.2.2-flatjar.jar
logstash_bin_dir: /opt/lib/logstash
logstash_chdir: /var/logstash
logstash_conf_dir: /etc/logstash.d
logstash_user: logstash
logstash_group: logstash

logstash_java_opts: ""
logstash_upstart_name: logstash

logstash_conf_file: "{{ logstash_conf_dir }}/{{ logstash_upstart_name }}.conf"

logstash_opts: "agent -f {{ logstash_conf_file }} -- web"
